### ISSUE TITLE
I am trying to Reproducing evaluation results

### ISSUE THREAD

**Issue by KA2010** [aerosec/jetset#1]
that what I got
<img width="1437" alt="Screen Shot 2021-10-13 at 2 03 45 PM" src="https://user-images.githubusercontent.com/70834906/137194873-b6cb4c69-d6bb-4247-9d91-ab3c2eaa6efe.png">
and when I run concrete file, I got
<img width="445" alt="Screen Shot 2021-10-13 at 2 49 32 PM" src="https://user-images.githubusercontent.com/70834906/137195044-6e65072b-fcc6-4bb4-a2ff-ab4712ed1033.png">

**Comment by enjhnsn2** [comment]
One thing that you can do with the generated emulator is fuzz it: the fuzzer we used is located here  https://github.com/aerosec/jetset_fuzzer .

**Comment by KA2010** [comment]
yes I already look at it, but how I can use it.
Is there is any guide that can help

**Comment by enjhnsn2** [comment]
The fuzzing repo README is pretty detailed, but we don't have anything like a quick start guide. The fuzzer just relies on AFL, so if you're familiar with AFL, it shouldn't be too hard to get started.

**Comment by maxwell-bland** [comment]
Adding to this, there is an example for how to perform syscall fuzzing at:
https://github.com/aerosec/jetset_fuzzer/blob/320b00f3982eb279568157c6213ee00b448f7707/example/cpu-exec.c#L162

At a high level, the steps to fuzzing are:
1. Add code to checkpoint the qemu emulator and read the fuzzer inputs into the cpu state
2. Initialize/build the docker image for the fuzzer (this isolating the fuzzer qemu instance from the OS itself, a necessary step because of how qemu is implemented)
3. Run the https://github.com/aerosec/jetset_fuzzer/blob/master/scripts/afl-fuzz-one.sh script to test a single instance of the fuzzer
4. (Optionally) https://github.com/aerosec/jetset_fuzzer/blob/master/scripts/afl-fuzz-many.sh to spin up several instances.

As Evan suggested, reading through the fuzzer's readme (and hopefully the code!) to make sure you understand how the system is working is strongly suggested. After reading the README, you might also get a lot of traction by reading through https://github.com/aerosec/jetset_fuzzer/blob/master/accel/tcg/afl-qemu-cpu-inl.c .
